" XDG configuration
set directory=$XDG_CACHE_HOME/vim
set backupdir=$XDG_CACHE_HOME/vim
set viminfo+=n$XDG_CACHE_HOME/viminfo
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after

" Plugins
execute pathogen#infect()
let g:airline_powerline_fonts = 1
set statusline+=%{fugitive#statusline()}

" UI options
set cursorline " Highlight the current line
set laststatus=2 " Always show status line
set mouse=a " Enable mouse input in all modes
set number " Enable line numbers
set showmatch " Show matching brackets
set wildmenu " Completion menu
set wildmode=list:longest

" Indentation options
set list listchars=tab:»\ ,trail:·
set noexpandtab
set autoindent
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=4
set tabstop=4

" Clipboard options
set clipboard+=unnamed " Yanks go on clipboard instead
set paste pastetoggle=<F10>

" Search options
set incsearch
set hlsearch
set ignorecase
set smartcase

" Remove trailing spaces on save
autocmd BufWritePre * :%s/\s\+$//e
