" Enable mouse input
set mouse=a

" Enable line numbers
set number

" Highlight all search terms
set hlsearch

" Indentation options
set list listchars=tab:»\ ,trail:·
set autoindent
set tabstop=4
set shiftwidth=4
set noexpandtab

" Clipboard options
set clipboard+=unnamed " Yanks go on clipboard instead
set pastetoggle=<F10>
set paste

" Completion options
set wildmenu
set wildmode=list:longest

" Search options
set incsearch
set hlsearch
set ignorecase

" XDG configuration
set viminfo+=n$XDG_CONFIG_HOME/vim/viminfo
set directory=$XDG_CACHE_HOME/vim
set backupdir=$XDG_CACHE_HOME/vim
